# Generated by Django 6.0 on 2026-01-05 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('menu_item_description', models.TextField(default='', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos_eleves/')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('guest_number', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('creneau', models.CharField(choices=[('08:00-10:00', '08:00 - 10:00'), ('10:00-12:00', '10:00 - 12:00'), ('14:00-16:00', '14:00 - 16:00'), ('16:00-18:00', '16:00 - 18:00')], max_length=50)),
            ],
            options={
                'unique_together': {('date', 'creneau')},
            },
        ),
    ]
